# Generated by Django 4.2.26 on 2025-12-09 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0006_alter_profession_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profession',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prof', to='mainpage.category'),
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название навыка')),
                ('description', models.TextField(blank=True, verbose_name='Описание навыка')),
                ('study_links', models.JSONField(blank=True, default=list, help_text='Список словарей в формате [{"title": "Название", "url": "ссылка"}, ...]', verbose_name='Ссылки для изучения')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Навык',
                'verbose_name_plural': 'Навыки',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='mainpage_sk_name_a4e1db_idx')],
            },
        ),
        migrations.AddField(
            model_name='profession',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='professions', to='mainpage.skill'),
        ),
    ]
